### ISSUE TITLE
Add youtube command

### ISSUE THREAD

**Issue by bravecobra** [mtheoryx/roberttables-livestream#1]
We'll a bot command to the youtube channel at either

https://www.youtube.com/user/mtheoryx83
or 
https://www.youtube.com/channel/UCh1LkG_3QNYncOLBriksY5Q

**Comment by mtheoryx** [comment]
Hooked up the command!

![screen shot 2019-01-05 at 10 38 20 am](https://user-images.githubusercontent.com/119065/50726087-1271bb80-10d6-11e9-9050-15df0d8c2025.png)
