### ISSUE TITLE
OBS Reset

### ISSUE THREAD

**Issue by parithon** [mtheoryx/roberttables-livestream#15]
As a suggestion, would it be possible to record your video from OBS using different channels for your MIC, computer and music? This way if your audio is cut for whatever reason from Twitch you can re-encode without the music track and upload after post processing?

**Comment by mtheoryx** [comment]
I took an initial look, and I think that the OBS setting for mkv would allow this, however, at this point in the stream I don't have the right tools, workflow, or time to fix this when it happens.
