### ISSUE TITLE
VS Code config deets

### ISSUE THREAD

**Issue by mampersat** [mtheoryx/roberttables-livestream#17]
I was inspired to start using VS code during today's stream and asking for advice on what plugins or tips/tricks you can share. 

The VS Code page has a lot of great info - but after watching your usage I'm kinda picking your brain for direction.

**Comment by mtheoryx** [comment]
Sure, I can get together an editor config type of a list. Appreciate the interest!

**Comment by mtheoryx** [comment]
Jeff Fritz got asked on his stream today, and he has them documented. I think this format would work for us, as well:

https://github.com/csharpfritz/Fritz.LiveStream/wiki/Frequently-Asked-Questions

**Comment by mtheoryx** [comment]
In the short term, here is a dump of all extensions I have installed:

https://gist.github.com/mtheoryx/e1673d3e4a20c7820661ed4840feb02b

**Comment by mtheoryx** [comment]
Have a fix for this incoming in a few minutes...

**Comment by mtheoryx** [comment]
Closed by #40

**Comment by mtheoryx** [comment]
For reference, here is the new page in the dev environment:

https://dev.roberttables.com/vscode/vscode-config/
