### ISSUE TITLE
Project Pages using stream notes markdown template

### ISSUE THREAD

**Issue by lannonbr** [mtheoryx/roberttables-livestream#45]
As mentioned in discord, the Project pages are using the stream note's template and such getting an incorrect title, but this can be tackled later.

_Originally posted by @lannonbr in https://github.com/mtheoryx/roberttables-livestream/pull/44#issuecomment-508951032_

**Comment by mtheoryx** [comment]
Fixed in PR #46 

Thanks again @lannonbr !

![bitmoji](https://render.bitstrips.com/v2/cpanel/8cc602bc-2866-4fd1-9827-83519ebed612-c3b45c6e-2943-4fd5-ab6e-fe23bffcb90b-v1.png?transparent=1&palette=1&width=246)
