### ISSUE TITLE
Create a list of current projects that are being developed on stream

### ISSUE THREAD

**Issue by lannonbr** [mtheoryx/roberttables-livestream#6]
Maybe have either it in a README or a markdown file specifically for projects.

Then we could have an archive and list a date range so if people want to watch old projects in the VOD, they know what timeframe it is in

**Comment by mtheoryx** [comment]
I've created this int he README, as well as added stream notes in there. I need to go back and correlate my videos to my notes, but here we go!

https://github.com/mtheoryx/roberttables-livestream/blob/master/README.md
