### ISSUE TITLE
Curated Streamers panel below stream

### ISSUE THREAD

**Issue by lannonbr** [mtheoryx/roberttables-livestream#7]
Have a panel below the stream have a curated list of streams from our community.

Maybe we can cycle it every so often so we can promote various streamers in the community

**Comment by mtheoryx** [comment]
We could possibly have a pretty stable list, but also a "featured" or "new streamers" or "charity streams" for events.

Thoughts on that?

**Comment by mtheoryx** [comment]
I created a streamer panel below the stream, as well as included the link to the Awesome Streamers repo so people can find even more.
